# Generated by Django 5.1.5 on 2025-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('indication', models.TextField()),
                ('classification', models.CharField(max_length=255)),
            ],
        ),
    ]
