# Generated by Django 5.1.5 on 2025-03-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_expiration_date_medicine_stocks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
    ]
