# Generated by Django 5.1.5 on 2025-03-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicine_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table=None,
        ),
    ]
