# Generated by Django 5.1.5 on 2025-08-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_medicine_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicines',
        ),
    ]
