# Generated by Django 5.1.5 on 2025-09-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_medicine_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='indication',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
    ]
