### Register a new user
POST http://127.0.0.1:8000/user/register/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDA4NzQyLCJpYXQiOjE3NDI2MzI3NDIsImp0aSI6IjY5Yjk3YWI3NDY2MjQ1MjJhYzNhZGM4NWFkOGIyMzI0IiwidXNlcl9pZCI6IjUiLCJpc19zdGFmZiI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjp0cnVlLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImZpcnN0X25hbWUiOiJBZG1pbiJ9.rx2coVwqmYNtT7indqtvkr4bp3qiwJ0WQSau7Zj9b4s

{
  "email": "entddoctor@hospital.com",
  "first_name": "John",
  "last_name": "Smith",
  "password": "securepassword456",
  "re_password": "securepassword456",
  "role": "doctor",
  "doctor_profile": {
      "specialization": "ENT",
      "schedules": [
          {
              "day_of_week": "Wednesday",
              "start_time": "08:30:00",
              "end_time": "10:30:00"
          },
          {
              "day_of_week": "Friday",
              "start_time": "08:30:00",
              "end_time": "10:30:00"
          }
      ]
  }
}
### admin request
GET http://127.0.0.1:8000//api/patients/${patientId}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDA4NzQyLCJpYXQiOjE3NDI2MzI3NDIsImp0aSI6IjY5Yjk3YWI3NDY2MjQ1MjJhYzNhZGM4NWFkOGIyMzI0IiwidXNlcl9pZCI6IjUiLCJpc19zdGFmZiI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjp0cnVlLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImZpcnN0X25hbWUiOiJBZG1pbiJ9.rx2coVwqmYNtT7indqtvkr4bp3qiwJ0WQSau7Zj9b4s



### admin request
GET  http://127.0.0.1:8000/user/doctors/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDA4NzQyLCJpYXQiOjE3NDI2MzI3NDIsImp0aSI6IjY5Yjk3YWI3NDY2MjQ1MjJhYzNhZGM4NWFkOGIyMzI0IiwidXNlcl9pZCI6IjUiLCJpc19zdGFmZiI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjp0cnVlLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImZpcnN0X25hbWUiOiJBZG1pbiJ9.rx2coVwqmYNtT7indqtvkr4bp3qiwJ0WQSau7Zj9b4s

### Login to obtain JWT tokens
POST http://localhost:8000/auth/jwt/create/
Content-Type: application/json

{
  "email": "secretaryaccount@gmail.com",
  "password": "nVmTfEkCFeB3APi"
}
###

### Login Secretary
POST http://localhost:8000/auth/jwt/create/
Content-Type: application/json

{
  "email": "cardiologist@hospital.com",
  "password": "securepassword123"
}

### Login Doctor
POST  http://localhost:8000/auth/jwt/create/
Content-Type: application/json

{
  "email": "generaldoctor@hospital.com",
  "password": "securepassword123"
}

### secretary request
POST   http://localhost:8000/bulk-add-dumm
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NzU3NjYxLCJpYXQiOjE3NTE5ODE2NjEsImp0aSI6IjVmZDRkYzNlYzMwYzQzNjFhYmEwMDllOTM4ZTQ1ZTY1IiwidXNlcl9pZCI6IkVFMkRZWFlZIiwiaXNfc3RhZmYiOmZhbHNlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJlbWFpbCI6InNlY3JldGFyeWFjY291bnRAZ21haWwuY29tIiwicm9sZSI6InNlY3JldGFyeSIsImZpcnN0X25hbWUiOiJMYXlsYSJ9.3uv35HQBPiH6_MocJNdehvFq8LfblguBaiV2o5QTnGk
### secretary request
GET    http://localhost:8000/medicine/predict/  
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NzU3NjYxLCJpYXQiOjE3NTE5ODE2NjEsImp0aSI6IjVmZDRkYzNlYzMwYzQzNjFhYmEwMDllOTM4ZTQ1ZTY1IiwidXNlcl9pZCI6IkVFMkRZWFlZIiwiaXNfc3RhZmYiOmZhbHNlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJlbWFpbCI6InNlY3JldGFyeWFjY291bnRAZ21haWwuY29tIiwicm9sZSI6InNlY3JldGFyeSIsImZpcnN0X25hbWUiOiJMYXlsYSJ9.3uv35HQBPiH6_MocJNdehvFq8LfblguBaiV2o5QTnGk 
### doctor request
GET   http://localhost:8000/appointment/upcoming-appointments/
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NzI2NjI0LCJpYXQiOjE3NTc5NTA2MjQsImp0aSI6IjczMGZjODQzNjI0ZTRhY2RiOTU5Y2FiYWM1M2I1NGU5IiwidXNlcl9pZCI6IkVFMkRZWFlZIiwiaXNfc3RhZmYiOmZhbHNlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJlbWFpbCI6InNlY3JldGFyeWFjY291bnRAZ21haWwuY29tIiwicm9sZSI6InNlY3JldGFyeSIsImZpcnN0X25hbWUiOiJMYXlsYSJ9.-fZy1A7TFBfehYDEVR66xk2DkxBFeemJBKbr8TGSwIU
### lab result upload 
