import { ThemeProvider } from "@/utils/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import { nunito } from "@/app/fonts";
import RouteProgress from "@/components/shared/route-progress";

export const metadata: Metadata = {
  title: "MediTrakk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nunito.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <RouteProgress />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
