# Generated by Django 5.1.5 on 2025-03-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('secretary', 'Medical Secretary'), ('admin', 'Admin')], default='doctor', max_length=20),
        ),
    ]
