# Generated by Django 5.1.5 on 2025-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_schedule_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
