# Generated by Django 5.1.5 on 2025-09-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_doctor_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('on-call-doctor', 'Oncall-Doctor'), ('secretary', 'Medical Secretary'), ('admin', 'Admin')], default='doctor', max_length=20),
        ),
    ]
