# Generated by Django 5.1.5 on 2025-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('on-call-doctor', 'Oncall-Doctor'), ('secretary', 'Medical Secretary'), ('admin', 'Admin')], default='doctor', max_length=20),
        ),
    ]
