# Generated by Django 5.1.5 on 2025-02-01 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=200, null=True)),
                ('temperature', models.CharField(blank=True, max_length=200, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('pulse_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('symptoms', models.TextField(max_length=200)),
                ('assessment', models.TextField(default='No assessment provided yet', max_length=200)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryStorageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('Regular', 'Regular'), ('Priority', 'Priority Lane (PWD/Pregnant)')], default='Regular', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Being Assessed', 'Being Assessed'), ('Queued for Treatment', 'Queued for Treatment'), ('Completed', 'Completed')], default='Waiting', max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporarystoragequeue', to='patient.patient')),
            ],
        ),
    ]
