# Generated by Django 5.1.5 on 2025-02-10 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='queue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='queue_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
