# Generated by Django 5.1.5 on 2025-02-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0003_preliminaryassessment_alcohol_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliminaryassessment',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='preliminaryassessment',
            name='current_symptoms',
        ),
    ]
