# Generated by Django 5.1.5 on 2025-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0004_remove_preliminaryassessment_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryassessment',
            name='assessment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
