# Generated by Django 5.1.5 on 2025-02-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_patient_complaint_alter_diagnosis_patient_and_more'),
        ('queueing', '0007_alter_temporarystoragequeue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='complaint',
            field=models.TextField(blank=True, choices=[('General Illness', 'General Illness'), ('Injury', 'Injury'), ('Check-up', 'Check-up'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminaryassessment', to='patient.patient'),
        ),
    ]
