# Generated by Django 5.1.5 on 2025-04-19 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_patient_gender'),
        ('queueing', '0008_temporarystoragequeue_complaint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporarystoragequeue', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Queued for Assessment', 'Queued for Assessment'), ('Queued for Treatment', 'Queued for Treatment'), ('Ongoing for Treatment', 'Ongoing for Treatment'), ('Completed', 'Completed')], default='Waiting', max_length=50),
        ),
    ]
