# Generated by Django 5.1.5 on 2025-02-26 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_patient_complaint_alter_diagnosis_patient_and_more'),
        ('queueing', '0008_temporarystoragequeue_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporarystoragequeue', to='patient.patient'),
        ),
    ]
