# Generated by Django 5.1.5 on 2025-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0009_alter_temporarystoragequeue_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Queued for Assessment', 'Queued for Assessment'), ('Queued for Treatment', 'Queued for Treatment'), ('Ongoing for Treatment', 'Ongoing for Treatment'), ('Completed', 'Completed')], default='Waiting', max_length=50),
        ),
    ]
