# Generated by Django 5.1.5 on 2025-04-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0009_treatment_doctor_alter_temporarystoragequeue_patient_and_more'),
        ('queueing', '0012_alter_treatment_doctor'),
    ]

    operations = [
    ]
