# Generated by Django 5.1.5 on 2025-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0014_alter_treatment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarystoragequeue',
            name='complaint',
            field=models.TextField(blank=True, choices=[('General Illness', 'General Illness'), ('Injury', 'Injury'), ('Check-up', 'Check-up'), ('Other', 'Other')], help_text="Either one of the predefined choices, or a custom text when 'Other'", max_length=100, null=True),
        ),
    ]
