# Generated by Django 5.1.5 on 2025-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0015_alter_temporarystoragequeue_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
