# Generated by Django 5.1.5 on 2025-09-24 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0017_alter_temporarystoragequeue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarystoragequeue',
            name='patient',
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='is_new_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_municipal_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='temp_street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
