# Generated by Django 5.1.5 on 2025-09-25 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patient_role_id'),
        ('queueing', '0018_remove_temporarystoragequeue_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarystoragequeue',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporarystoragequeue', to='patient.patient'),
        ),
    ]
