# Generated by Django 5.1.5 on 2025-04-21 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patient', '0012_patient_gender'),
        ('user', '0009_doctor_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date'), name='unique_appointment_per_doctor_and_slot'),
        ),
    ]
