# Generated by Django 5.1.5 on 2025-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaint',
            field=models.TextField(blank=True, choices=[('General Illness', 'General Illness'), ('Injury', 'Injury'), ('Check-up', 'Check-up'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
