# Generated by Django 5.1.5 on 2025-03-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_labresult_patient_labresult_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
