# Generated by Django 5.1.5 on 2025-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted')], default='Pending', max_length=50),
        ),
    ]
