# Generated by Django 5.1.5 on 2025-08-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
