# Generated by Django 5.1.5 on 2025-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role_id',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
