# Generated by Django 5.1.5 on 2025-08-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_migrate_name_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
