// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data

import { Doctor } from "@/components/molecules/tables/doctor-columns";
import { Operation } from "@/app/admin/components/operation-columns";
import { User } from "@/app/designer/columns";
import { Registration } from "@/app/secretary/registration-queue/columns";
import { Appointment } from "@/app/patient/(appointments)/columns";
import { DocumentFile } from "@/app/patient/documents/columns";
import { Prescription } from "@/app/patient/prescriptions/columns";
import { Calendar, Mail, UserPlus } from "lucide-react";
import { NotificationType } from "@/components/molecules/header/notification";

export const registrations: Registration[] = [
  {
    queue_number: "#05",
    name: "Juan Dela Cruz",
    type: "Consultation",
    time: "4:00 pm",
  },
    {
    queue_number: "#06",
    name: "Juan Dela Cruz",
    type: "Consultation",
    time: "4:00 pm",
  },
]

export const appointments: Appointment[] = [
  {
    patient_name: "Juan Dela Cruz",
    doctor_name: "Dr. Maria Santos",
    date: "2025-09-01",
    start_time: "09:00",
    end_time: "09:30",
    location: "Room 101",
    status: "Scheduled",
  },
  {
    patient_name: "Ana Reyes",
    doctor_name: "Dr. Jose Ramirez",
    date: "2025-09-01",
    start_time: "10:00",
    end_time: "10:45",
    location: "Room 102",
    status: "Completed",
  },
  {
    patient_name: "Carlos Mendoza",
    doctor_name: "Dr. Liza Cruz",
    date: "2025-09-02",
    start_time: "11:00",
    end_time: "11:30",
    location: "Room 103",
    status: "Cancelled",
  },
  {
    patient_name: "Sofia Lopez",
    doctor_name: "Dr. Manuel Torres",
    date: "2025-09-02",
    start_time: "13:00",
    end_time: "13:30",
    location: "Room 104",
    status: "Scheduled",
  },
  {
    patient_name: "Miguel Garcia",
    doctor_name: "Dr. Elena Flores",
    date: "2025-09-03",
    start_time: "14:00",
    end_time: "14:45",
    location: "Room 105",
    status: "Scheduled",
  },
  {
    patient_name: "Isabella Cruz",
    doctor_name: "Dr. Roberto Mendoza",
    date: "2025-09-03",
    start_time: "15:00",
    end_time: "15:30",
    location: "Room 106",
    status: "Completed",
  },
  {
    patient_name: "Gabriel Ramos",
    doctor_name: "Dr. Patricia Castillo",
    date: "2025-09-04",
    start_time: "09:30",
    end_time: "10:00",
    location: "Room 107",
    status: "Scheduled",
  },
  {
    patient_name: "Camila Fernandez",
    doctor_name: "Dr. Victor Hernandez",
    date: "2025-09-04",
    start_time: "11:00",
    end_time: "11:30",
    location: "Room 108",
    status: "Rescheduled",
  },
  {
    patient_name: "Diego Santos",
    doctor_name: "Dr. Andrea Gutierrez",
    date: "2025-09-05",
    start_time: "13:00",
    end_time: "13:45",
    location: "Room 109",
    status: "Scheduled",
  },
  {
    patient_name: "Lucia Morales",
    doctor_name: "Dr. Ramon Perez",
    date: "2025-09-05",
    start_time: "14:30",
    end_time: "15:00",
    location: "Room 110",
    status: "Completed",
  },
  {
    patient_name: "Antonio Delgado",
    doctor_name: "Dr. Cristina Alvarez",
    date: "2025-09-06",
    start_time: "16:00",
    end_time: "16:30",
    location: "Room 111",
    status: "Scheduled",
  },
];


export const prescriptions: Prescription[] = [
  {
    prescription_id: "RX001",
    patient_name: "John Doe",
    doctor_name: "Dr. Smith",
    medicine_name: "Amoxicillin",
    dosage: "500mg",
    frequency: "3 times a day",
    duration: "7 days",
    instructions: "Take after meals with water",
    date_issued: "2025-08-20",
    status: "active",
  },
  {
    prescription_id: "RX002",
    patient_name: "Jane Miller",
    doctor_name: "Dr. Adams",
    medicine_name: "Paracetamol",
    dosage: "500mg",
    frequency: "Every 6 hours as needed",
    duration: "5 days",
    instructions: "Do not exceed 4g per day",
    date_issued: "2025-08-18",
    status: "completed",
  },
  {
    prescription_id: "RX003",
    patient_name: "Michael Johnson",
    doctor_name: "Dr. Patel",
    medicine_name: "Ibuprofen",
    dosage: "400mg",
    frequency: "2 times a day",
    duration: "10 days",
    instructions: "Take with food to avoid stomach upset",
    date_issued: "2025-08-22",
    status: "active",
  },
];

export const documents: DocumentFile[] = [
  {
    document_id: "1",
    title: "Student Handbook",
    description: "Official student guidelines for 2025",
    file_url: "/documents/student-handbook.pdf",
    file_type: "PDF",
    uploaded_by: "Admin",
    created_at: "2025-08-01",
    updated_at: "2025-08-01",
    status: "active",
  },
  {
    document_id: "2",
    title: "Medical Report",
    description: "Annual physical examination results",
    file_url: "/documents/medical-report.docx",
    file_type: "DOCX",
    uploaded_by: "Dr. Smith",
    created_at: "2025-08-10",
    updated_at: "2025-08-15",
    status: "archived",
  },
  {
    document_id: "3",
    title: "Event Poster",
    description: "Poster for upcoming campus event",
    file_url: "/documents/event-poster.jpg",
    file_type: "JPG",
    uploaded_by: "Student Council",
    created_at: "2025-08-20",
    updated_at: "2025-08-22",
    status: "active",
  },
];

export const doctors: Doctor[] = [
  {
    name: "Dr. Smith",
    specialization: "Cardiology",
    days_available: "Mon, Wed, Fri",
    working_hours: "09:00 - 17:00",
    status: "active",
  },
  {
    name: "Dr. Johnson",
    specialization: "Dermatology",
    days_available: "Tue, Thu",
    working_hours: "10:00 - 16:00",
    status: "active",
  },
  {
    name: "Dr. Williams",
    specialization: "Pediatrics",
    days_available: "Mon - Fri",
    working_hours: "08:00 - 15:00",
    status: "on leave",
  },
  {
    name: "Dr. Brown",
    specialization: "Orthopedics",
    days_available: "Wed, Thu, Sat",
    working_hours: "11:00 - 18:00",
    status: "active",
  },
  {
    name: "Dr. Davis",
    specialization: "Neurology",
    days_available: "Mon, Tue, Fri",
    working_hours: "09:30 - 17:30",
    status: "inactive",
  },
  {
    name: "Dr. Miller",
    specialization: "General Medicine",
    days_available: "Mon - Sat",
    working_hours: "07:00 - 14:00",
    status: "active",
  },
];


export const users = [
  {
    id: 1,
    email: "alice.smith@example.com",
    first_name: "Alice",
    last_name: "Smith",
    role: "admin",
    is_active: true,
  },
  {
    id: 2,
    email: "bob.jones@example.com",
    first_name: "Bob",
    last_name: "Jones",
    role: "doctor",
    is_active: true,
  },
  {
    id: 3,
    email: "carol.taylor@example.com",
    first_name: "Carol",
    last_name: "Taylor",
    role: "secretary",
    is_active: false,
  },
  {
    id: 4,
    email: "david.lee@example.com",
    first_name: "David",
    last_name: "Lee",
    role: "doctor",
    is_active: true,
  },
  {
    id: 5,
    email: "ella.wilson@example.com",
    first_name: "Ella",
    last_name: "Wilson",
    role: "secretary",
    is_active: true,
  },
  {
    id: 6,
    email: "frank.miller@example.com",
    first_name: "Frank",
    last_name: "Miller",
    role: "admin",
    is_active: false,
  },
  {
    id: 7,
    email: "grace.davis@example.com",
    first_name: "Grace",
    last_name: "Davis",
    role: "doctor",
    is_active: true,
  },
  {
    id: 8,
    email: "henry.moore@example.com",
    first_name: "Henry",
    last_name: "Moore",
    role: "secretary",
    is_active: true,
  },
  {
    id: 9,
    email: "isla.anderson@example.com",
    first_name: "Isla",
    last_name: "Anderson",
    role: "admin",
    is_active: true,
  },
  {
    id: 10,
    email: "jack.white@example.com",
    first_name: "Jack",
    last_name: "White",
    role: "doctor",
    is_active: false,
  },
  {
    id: 11,
    email: "kate.harris@example.com",
    first_name: "Kate",
    last_name: "Harris",
    role: "secretary",
    is_active: true,
  },
] as const satisfies User[];

export const operations: Operation[] = [
  {
    patient_name: "Alice Johnson",
    date: "20-08-2019",
    duration: "1.5 hours",
    type: "General",
    follow_up_date: "20-09-2019",
    condition: "Appendicitis",
  },
  {
    patient_name: "Robert Brown",
    date: "25-08-2019",
    duration: "2 hours",
    type: "Local",
    follow_up_date: "25-09-2019",
    condition: "Hernia",
  },
  {
    patient_name: "Sophia Clark",
    date: "30-08-2019",
    duration: "2.5 hours",
    type: "General",
    follow_up_date: "30-09-2019",
    condition: "Gallstones",
  },
  {
    patient_name: "Liam Davis",
    date: "05-09-2019",
    duration: "2 hours",
    type: "Local",
    follow_up_date: "05-10-2019",
    condition: "Knee Injury",
  },
  {
    patient_name: "Emma Wilson",
    date: "10-09-2019",
    duration: "1 hour",
    type: "Local",
    follow_up_date: "10-09-2019",
    condition: "Cataract",
  },
  {
    patient_name: "Olivia Martinez",
    date: "15-09-2019",
    duration: "4 hours",
    type: "General",
    follow_up_date: "15-10-2019",
    condition: "Cardiac",
  },
  {
    patient_name: "William Johnson",
    date: "20-09-2019",
    duration: "5 hours",
    type: "General",
    follow_up_date: "20-10-2019",
    condition: "Spinal",
  },
  {
    patient_name: "Mia Brown",
    date: "25-09-2019",
    duration: "3 hours",
    type: "General",
    follow_up_date: "25-10-2019",
    condition: "Obesity",
  },
];

export const notifications: NotificationType[] = [
  {
    id: 1,
    title: "Please check your email",
    time: "14 mins ago",
    icon: Mail,
    color: "text-green-500",
  },
  {
    id: 2,
    title: "New patient added",
    time: "22 mins ago",
    icon: UserPlus,
    color: "text-green-500",
  },
  {
    id: 3,
    title: "Your leave is approved!",
    time: "3 hours ago",
    icon: Calendar,
    color: "text-blue-500",
  },
];